### ISSUE TITLE
The book of the dead?

### ISSUE THREAD

**Issue by geyslan** [c0defellas/c.in.fork.book#15]
Hello folks,

@tiago4orion @patito @CoolerVoid @felipensp @raphaelsc @pedrofausto

I don't like too much retaining dead projects. So, is there any good soul who want to take care of it? Or can I push the _**go to hell**_ button in this?

**Comment by coffnix** [comment]
Virjão,

Não mata o projeto não mano! deixa como tá e fodas hauahuahuahuahuauhauha
Ou pica ele em vários mini-artigos e publica semanalmente, ou pica em
artigos menores com o que tem e lança umas zine. :D


Att,
Raphael Bastos aka Tyresix

*====================================================*
*email:~> $* echo "xgvngkrhgyzuyFngiqyzuxk4ius4hx" | perl -pe \
's/(.)/chr(ord($1)-2*3)/ge'
*Public Key:* 3FBB468B //
https://www.area31.net.br/tyresix/other/tyresix-pgp-key.txt
<http://www.hackstore.com.br/coffnix/coffnix-pgp-key.txt>
*Wiki Hackstore* - https://wiki.hackstore.com.br
<http://wiki.hackstore.com.br/>
*Área 31 Hackerspace* - https://www.area31.net.br <http://www.area31.net.br>
*====================================================*

2017-01-10 9:09 GMT-02:00 Geyslan Gregório Bem <notifications@github.com>:

**Comment by geyslan** [comment]
@coffnix 

That can be a solution. However, nowadays I'm engaged in other projects, so I can't go on with C in Fork book.

**Comment by raphaelsc** [comment]
@geyslan Mantém ele vivo. Essa é alma do open source. Você não tem tempo p/ continuar, mas alguém pode ter.

**Comment by geyslan** [comment]
@c0defellas 

>So, is there any good soul who want to take care of it?

:smile:

**Comment by raphaelsc** [comment]
just wait for it =) no rush

**Comment by pedrofausto** [comment]
A guy with no spare time is asking: "Can we try one more time?"

**Comment by geyslan** [comment]
I would dare to try!
